#!/bin/bash

OUT="$1"

if [ "$OUT" = "" ]; then
   echo "Usage: $0 /path/to/output.tar.gz"
   exit
fi


TEMP=/tmp/fwprofile-$$
while [ -e "$TEMP" ]; do
   TEMP="$TEMP"x
done

mkdir -p $TEMP
cp -a * $TEMP
sed -i "s/slaxpasswrd61//" $TEMP/config.php
sed -i "s/slax/root/" $TEMP/config.php
rm -Rf $TEMP/.git
rm $TEMP/makepkg $TEMP/ROADMAP.html $TEMP/README.md

(cd $TEMP; tar -c *) | gzip -f --best > $OUT
rm -Rf $TEMP

